apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-config.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm-config.name" . }}
    helm.sh/chart: {{ include "helm-config.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range .Values.configmap.data }}
  {{ .key }}: "{{ .value }}"
  {{- end }}